@startuml
start

if (Первый запуск программы?) then (да)
    if (Выбрать папку по умолчанию?) then (нет)
        :;
        label choose
        : Указываем пустую папку\n или ранее существовавшую\n с настройками программы;
    endif
else (нет)
    if (Выбрать новую папку для настроек?) then (да)
        :;
        goto choose
    endif
endif
: Папка с настройками выбрана;
if (В программе есть пользователи?) then (нет)
    : \n\n;
     label create
    : Создаем нового пользователя;
    : Указываем тип (студент или преподаватель);
    : Указываем ФИО;
else (да)
    if (Создать нового или\nвыбрать существующего?) then (выбрать)
    else (создать нового)
        :;
        goto create
    endif
endif
: Пользователь выбран;
: Вход в программу;
stop
@enduml