@startuml

|Программа|
:Создать папку с настройками;
:Создать аккаунт преподавателя;
|Преподаватель|
:Выложить задание;
|Студент|
:Загрузить рисунок для задания;
|Программа|
:Создать аккаунт студента;
|Программа|
:Автоматическая проверка\nна плагиат и соответствие заданию;
|Преподаватель|
:Проверить работу студента;
|Студент|
if (Работа отклонена?) then (да)
  :Студент исправляет работу;
  stop
else (нет)
    :Ждет следующего задания;
  stop
endif

@enduml