@startuml
actor Student
activate Student
Student -> Main: запустить программу
activate Main
Main -> ConfigController: initialize
activate ConfigController
ConfigController --> Main: Настройки загружены
deactivate ConfigController
Main -> UserManager: create_user_dialog or\n choose_user_dialog
activate UserManager
UserManager --> Main: Пользователь выбран
deactivate UserManager
Main -> TaskManager: choose_task_dialog
activate TaskManager
TaskManager --> Main: Студентом выбрано задание
deactivate TaskManager
Main -> PaintManager: create_paint_dialog
activate PaintManager
PaintManager -> UniqueSearchModel: find_duplicates
activate UniqueSearchModel
UniqueSearchModel --> PaintManager: Проверен на плагиат
deactivate UniqueSearchModel
PaintManager -> SimilarityModel: compare_paint_and_task
activate SimilarityModel
SimilarityModel --> PaintManager: Было определено соответствие задания и рисунка
deactivate SimilarityModel
PaintManager --> Main: Рисунок для выбранного задания загружен
deactivate PaintManager
Main -> PaintManager: checked_works_dialog
activate PaintManager
PaintManager --> Main: Студент исправляет отправленные на доработку рисунки
deactivate PaintManager
Main -> ConfigController: save_on_close
activate ConfigController
ConfigController --> Main: Приложение сохранено
deactivate ConfigController
Student <- Main: завершение программы
deactivate Main
deactivate Student
@enduml