@startuml

title Activity Diagram: Определение того, \nсоответствует ли картина указанному заданию

start
:Генерация описаний с использованием Image Caption моделей;
:Запись результатов в en_generated_captions;
:Перевод описаний на русский язык с помощью Helsinki-NLP/opus-mt-en-ru;
:Запись результатов в ru_generated_captions;
if (Сравнение сгенерированного описания)
  :с правильным описанием задания;
  :Запись значения сходства в similarities;
  if (Сходство > 0.59) then (Да)
     :система определила верно:\nправильный текст задания\nсовпадает с изображением;
   else (Нет)
     :система ошиблась и решила,\nчто правильный текст\nне совпадает с изображением;
   endif
else
  :с неправильным описанием задания;
  :Запись значения сходства в wrong_similarities;
  if (Сходство > 0.59) then (Да)
     :система ошиблась и решила,\nчто неправильный текст\nсовпадает с изображением;
   else (Нет)
     :система определила верно:\nнеправильный текст\nне совпадает с изображением;
   endif
endif
:Результаты записываются в result_answers;
stop

@enduml